### ISSUE TITLE
Dashboards missing from drop down

### ISSUE THREAD

**Issue by aaronJokhun** [dashbuilder/dashbuilder#175]
When i create a new dashboard, log off and back in again, the dashboard is not available in the drop down. It does appear after you create another new dashboard.

**Comment by jhrcek** [comment]
@aaronJokhun Could you be more specific, please? What do you mean by "creating dashboard". Do you mean workspace? And what dropdown do you mean specifically? Could you please attach a screenshot marking the dropdown where you expect to see the "dashboard"?

I tried creating new workspace, logging out and then back in and the workspace was listed (see screenshot)
![creatingworkspace](https://cloud.githubusercontent.com/assets/2716069/14808415/3a7cb480-0b85-11e6-94e9-1067dd5a9f65.png)
).

**Comment by aaronJokhun** [comment]
@jhrcek I am using dashbuilder-distros-0.4.0, your screenshot looks quite different to mine. I have pointed out the dashboard drop down in the screenshot. 

![dashbuilder](https://cloud.githubusercontent.com/assets/18661691/14878714/87b6139e-0d25-11e6-85ca-ecadb62a4eb3.png)

**Comment by carlosedubarreto** [comment]
@aaronJokhun This problem was already solved in version 0.6.
Now, it seems that the drag and drop is not working anymore.
