### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by carlosedubarreto** [dashbuilder/dashbuilder#215]
I´m testing version 0.6 and notice that the drag and drop is not working anymore as it was in versions 0.4 and 0.5

**Comment by dgutierr** [comment]
Unfortunately, the drag&drop feature is currently broken on master:

https://issues.jboss.org/browse/UF-277

We will try to provide a fix asap.

- David -

**Comment by todhunter** [comment]
when you plan to fix this bug?

**Comment by davis-varghese** [comment]
is there any workaround to dashboard(other than programming using API). This is a major blocker

**Comment by dgutierr** [comment]
You can use the new content management features (still under heavy development though, see => https://www.youtube.com/watch?v=51ETHDJsjtA). Actually, this new approach for creating dashboard will replace the old one.

**Comment by davis-varghese** [comment]
Looks very good :). Is there a branch where I can try this out. Could you please share few other youtube links of the upcoming features. Thanks

**Comment by dgutierr** [comment]
Ongoing development features are hosted in master branch.

Navigation widgets => https://www.youtube.com/watch?v=eItjBB4j0CY
Custom Metric displayers => https://www.youtube.com/watch?v=Mto0qvjkNoI
Security management => https://www.youtube.com/watch?v=S4HCTuAmqGA
