### ISSUE TITLE
not show security navigation use uberfire 

### ISSUE THREAD

**Issue by tienduong1988** [dashbuilder/dashbuilder#265]
I downloaded uf dashbuilder for EAP at here: http://dashbuilder.org/downloads/downloads_ufdashb.html, but when i deployed success, in dashboard navigation not show security management, please help me solve it, thanks

**Comment by jhrcek** [comment]
@tienduong1988 It seems that the download page doesn't contain the most up to date link.
You can try the following [link](https://origin-repository.jboss.org/nexus/service/local/artifact/maven/redirect?r=snapshots&g=org.dashbuilder&a=dashbuilder-distros&v=0.6.0-SNAPSHOT&e=war&c=wildfly10), you'll get the latest 0.6.0 snapshot.

However I'm not sure that dashbuilder distribution contains the security management feature in the UI, does it @dgutierr?

**Comment by dgutierr** [comment]
That's right @Jan!

Security management is included in the latest snapshot.

Thanks for pointing this out,

- David -

**Comment by tienduong1988** [comment]
Yeah,  thanks for support
