### ISSUE TITLE
JDK 1.8 required 

### ISSUE THREAD

**Issue by achabahe** [dashbuilder/dashbuilder#268]
you should update the required JDK in the README file because it can not be compiled in jdk7 or lower the only jdk supported is the 1.8 because in the interface org/dashbuilder/dataprovider/DataSetProviderType.java 
there is a use of the default method and this feature exist only in jdk8 and above

**Comment by ghugan** [comment]
i have tried with jdk 1.9 and its not working..switch back to 1.8 and it worked
