### ISSUE TITLE
Oracle DataSource Date Field Appearing Blank

### ISSUE THREAD

**Issue by mnarang123** [dashbuilder/dashbuilder#320]
Dear UF Dashbuilder Team,

I added a SQL query for Oracle data source in  UF Dashbuilder 0.6.0 Snapshot for widlfly10. Date column information in the table preview region and while using in perspective is appearing blank. Date format in Oracle is DD-Mon-YYYY.

Thank you.

**Comment by jhrcek** [comment]
@mnarang123 Could you please provide some details? I would be nice to have:
the query you're using, the schema of the table(s) you're querying and screenshot of the data set preview (after you click the Test button when creating the data set) to see what data types were identified for individual columns in the data set..

**Comment by mnarang123** [comment]
Thanks for your response. Please find SQL query and screenshots.

SELECT request_id,       status_desc,       last_update_date   FROM xxhr_dcl_request_v


![preview](https://cloud.githubusercontent.com/assets/22834243/25885168/fce10b90-3567-11e7-8702-536fc4db8e72.png)
![oracle query](https://cloud.githubusercontent.com/assets/22834243/25885169/fce6e9f2-3567-11e7-8101-efd7cd60dbba.png)
![dataset](https://cloud.githubusercontent.com/assets/22834243/25885170/fcecaaa4-3567-11e7-80e9-198a76769092.png)

**Comment by jlosantana** [comment]
the only formats allowed:

public static final String PATTERN_YEAR = "YYYY";
    public static final String PATTERN_MONTH = "YYYY-MM";
    public static final String PATTERN_DAY = "YYYY-MM-DD";
    public static final String PATTERN_HOUR = "YYYY-MM-DD HH24";
    public static final String PATTERN_MINUTE = "YYYY-MM-DD HH24:MI";
    public static final String PATTERN_SECOND = "YYYY-MM-DD HH24:MI:SS";

use one of then and will work!
