### ISSUE TITLE
Sorting Issue 

### ISSUE THREAD

**Issue by mnarang123** [dashbuilder/dashbuilder#329]
Dear Team,

I have noticed that chart category axis is not sorted by the category column.  value. Example x axis column in the attached screenshot is not sorted by year value
![snap 2017-05-25 at 13 32 20](https://cloud.githubusercontent.com/assets/22834243/26444757/c46ac574-414e-11e7-92b7-e15c27dd27e1.png)

**Comment by mnarang123** [comment]
@jhrcek, can you please help me with this issue? Am i missing something while configuration?

**Comment by jhrcek** [comment]
@dgutierr This looks like one of those missing features - X axis sort order cannot be determined/configured anywhere. Should I report this to dashbuilder jira or is it configurable somewhere?

**Comment by mnarang123** [comment]
Dear @dgutierr  Please help me with this issue. Even default sorting will be fine.

**Comment by dgutierr** [comment]
Moved to JIRA => https://issues.jboss.org/browse/DASHBUILDE-232
