### ISSUE TITLE
Offline or lan required

### ISSUE THREAD

**Issue by vipcxj** [dashbuilder/dashbuilder#332]
The gwt charts does not work under offline or lan environment. And in some area, the google site is blocked as well.

**Comment by jhrcek** [comment]
@dgutierr I've seen similar requests to make dashbuilder work offline several times. But checking this [Google charts FAQ](https://developers.google.com/chart/interactive/faq#offline) i see that this is impossible. Can we do something about that?

**Comment by vipcxj** [comment]
I found there are sevel charts implements in dashbuilder project. Is there a way to switch google implements to nvd3 or ofc2? My jbpm version is 6.5.0.Final
