### ISSUE TITLE
How to create new users for UF-Dashbuilder.

### ISSUE THREAD

**Issue by bugcy013** [dashbuilder/dashbuilder#41]
Hi Guys,

Currently I am using UF-Dashbuilder it's pretty cool, currently I am struggling with creating new user, and creating access control for different user profiles for dashboard access. 
Please guide me. how to do that.

-Dhanasekaran.

**Comment by dgutierr** [comment]
UF Dashbuilder relies on app server authentication. For user/role management please read the following [instructions](https://github.com/dashbuilder/dashbuilder/blob/master/dashbuilder-distros/src/main/wildfly8/README.md#user-authentication). As for grant/deny access to dashboards authored from the tooling is something we currently lack. Permission management features will be delivered on next major release.
