### ISSUE TITLE
Build Failure : COMPILATION ERROR at PerspectivePluginManager.java:[157,60]

### ISSUE THREAD

**Issue by malathimunesh** [dashbuilder/dashbuilder#421]
Hi,

I'm following  README.md of "**dashbuilder-distros**" and trying to Run the maven build on the root path for the project using command "**$ mvn clean install -DskipTests -Dfull**"

Build is failing with the following error :

[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/dashbuilder/dashbuilder/dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/plugin/PerspectivePluginManager.java:[157,60] incompatible types: org.uberfire.ext.layout.editor.api.editor.LayoutInstance cannot be converted to com.google.gwt.user.client.ui.IsWidget
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Dashbuilder BOM (Bill Of Materials) ................ SUCCESS [  5.754 s]
[INFO] Dashbuilder Project ................................ SUCCESS [01:12 min]
[INFO] Dashbuilder Backend ................................ SUCCESS [  0.135 s]
[INFO] Dashbuilder SQL Tests .............................. SUCCESS [ 28.555 s]
[INFO] Dashbuilder Dataset Core CDI support ............... SUCCESS [04:02 min]
[INFO] Dashbuilder Shared ................................. SUCCESS [  0.130 s]
[INFO] Dashbuilder Navigation API ......................... SUCCESS [ 31.701 s]
[INFO] Dashbuilder Navigation Backend ..................... SUCCESS [ 12.630 s]
[INFO] Dashbuilder Services API ........................... SUCCESS [  0.924 s]
[INFO] Dashbuilder Services ............................... SUCCESS [ 14.500 s]
[INFO] Dashbuilder Displayer API .......................... SUCCESS [  1.107 s]
[INFO] Dashbuilder Client modules ......................... SUCCESS [  0.090 s]
[INFO] Dashbuilder Common Client .......................... SUCCESS [03:43 min]
[INFO] Dashbuilder Dataset Client ......................... SUCCESS [ 20.860 s]
[INFO] Dashbuilder Validations ............................ SUCCESS [  6.844 s]
[INFO] Dashbuilder Displayer Client ....................... SUCCESS [ 13.007 s]
[INFO] Dashbuilder Renderer Libraries ..................... SUCCESS [  0.120 s]
[INFO] Dashbuilder Default Renderer ....................... SUCCESS [  4.022 s]
[INFO] Dashbuilder Widgets ................................ SUCCESS [  4.439 s]
[INFO] Dashbuilder Data Set Editor ........................ SUCCESS [  6.710 s]
[INFO] Dashbuilder Displayer Screen ....................... SUCCESS [  1.890 s]
[INFO] Dashbuilder Displayer Editor Widgets ............... SUCCESS [ 12.788 s]
[INFO] Dashbuilder Renderer Google ........................ SUCCESS [  4.895 s]
[INFO] Dashbuilder Renderer ChartJS ....................... SUCCESS [  1.642 s]
[INFO] Dashbuilder Renderer Lienzo ........................ SUCCESS [ 10.619 s]
[INFO] Dashbuilder Navigation Client ...................... FAILURE [ 15.989 s]
[INFO] Dashbuilder CMS Client ............................. SKIPPED
[INFO] Dashbuilder Packaging .............................. SKIPPED
[INFO] Dashbuilder All Client Libraries ................... SKIPPED
[INFO] Dashbuilder All Server Libraries ................... SKIPPED
[INFO] Dashbuilder All Libraries .......................... SKIPPED
[INFO] Dashbuilder WebApp ................................. SKIPPED
[INFO] Dashbuilder Distribution WARs ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:22 min
[INFO] Finished at: 2018-06-13T16:29:49+05:30
[INFO] Final Memory: 183M/913M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project dashbuilder-navigation-client: Compilation failure
[ERROR] /home/dashbuilder/dashbuilder/dashbuilder-client/dashbuilder-navigation-client/src/main/java/org/dashbuilder/client/navigation/plugin/PerspectivePluginManager.java:[157,60] incompatible types: org.uberfire.ext.layout.editor.api.editor.LayoutInstance cannot be converted to com.google.gwt.user.client.ui.IsWidget
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dashbuilder-navigation-client

**Comment by jdamianb** [comment]
I found the same problem trying out in a windows 10 pc with maven 3.5.4 and JDK 1.8.0_181

**Comment by deepak9897** [comment]
Is this issue resolved.
I have also the same.

**Comment by opendatasurgeon** [comment]
I have same issue.
