### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by opendatasurgeon** [dashbuilder/dashbuilder#426]
Hello, I am having several issues, pretty much identical to #421 

I was wondering if this project is still active. Thank you!

**Comment by ederign** [comment]
HI @opendatasurgeon no it's not!

DashBuilder project is active and innovating at a fast pace!

DashBuilder project is active and innovating at a fast pace! But how can I keep you with the new features?

First, we have a new blog home [blog.kie.org](https://blog.kie.org/). This blog is the best place to keep you updated with new features.

You can also check out this [blog post](https://blog.kie.org/2021/04/dashbuilder-an-apache-licensed-business-reporting-and-monitoring-tool.html) to see a summary of the most exciting DashBuilder new features or follow the [Getting Started Guide](https://blog.kie.org/2021/05/dashbuilder-getting-started-guide.html).

The source code of this project is living mostly on [Appformer](https://github.com/kiegroup/appformer). The dashbuilder-dataset modules have moved to [kie-soup](https://github.com/kiegroup/kie-soup)

**Comment by mihirp161** [comment]
Thanks for letting me know @ederign  :)

**Comment by ederign** [comment]
@opendatasurgeon yw! and sorry again for the delay! Please take a look on our blog posts and we are open for feature suggestions!

**Comment by mihirp161** [comment]
No worries, appreciate it.
